trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - ml-service/*

pool:
  name: Azure Pipelines
#Your build pipeline references an undefined variable named ‘Parameters.connectedServiceNameARM’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.connectedServiceNameARM’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘workspaceName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘workspaceName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘resourceGroupName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘Parameters.connectedServiceNameARM’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘runConfig’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘runConfig’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘modelName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘modelName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘modelAssetPath’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘Parameters.connectedServiceNameARM’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘serviceName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘serviceName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘aksComputeName’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
variables:
  inferenceConfigFile: 'inferenceConfig.yml'
  deploymentConfigFile: 'deploymentConfig.yml'

steps:
- task: AzureCLI@1
  displayName: 'Install Azure CLI ML Extension'
  inputs:
    azureSubscription: '$(connectedServiceNameARM)'
    scriptLocation: inlineScript
    inlineScript: |
     # Install the Azure ML CLI extension (Learn more: https://aka.ms/aml-cli).
     az extension add -n azure-cli-ml

- task: AzureCLI@1
  displayName: Setup
  inputs:
    azureSubscription: '$(connectedServiceNameARM)'
    scriptLocation: inlineScript
    inlineScript: |
     # Attach a workspace configuration to a folder to enable CLI contextual awareness (Learn more: https://aka.ms/aml-cli-resource).
     az ml folder attach -w $(workspaceName) -g $(resourceGroupName)

- task: AzureCLI@1
  displayName: 'Train Model'
  inputs:
    azureSubscription: '$(connectedServiceNameARM)'
    scriptLocation: inlineScript
    inlineScript: |
     # Start a run of the experiment (Learn more: https://aka.ms/aml-cli-run).
     { az ml run submit-script -c $(runConfig) -t runmetadata.json; } &&
     # Register a model with Azure Machine Learning (Learn more: https://aka.ms/aml-cli-model).
     { az ml model register -n $(modelName) --asset-path $(modelAssetPath) -f runmetadata.json -t modelmetadata.json; }

- task: AzureCLI@1
  displayName: 'Deploy Model'
  inputs:
    azureSubscription: '$(Parameters.connectedServiceNameARM)'
    scriptLocation: inlineScript
    inlineScript: |
     # Deploy the registered model to AKS (Learn more: https://aka.ms/aml-cli-model).
     az ml model deploy -n $(serviceName) --overwrite -f modelmetadata.json --ic $(inferenceConfigFile) --dc $(deploymentConfigFile) --ct $(aksComputeName)
