apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: mhew-mltest-iris
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: release
  components:
    - name: mltest-iris
      image: mhewmlservicew8204786564.azurecr.io/mltest-iris-sklearn:1
      ports:
        - name: http
          port: 5001
      publicPort: http
  privateImageHubs:
    mhewmlservicew8204786564.azurecr.io:
      username: 45df7a08-56f9-4651-9881-754a84b9f29b
      email: mark_a_hewitt@yahoo.co.uk
